# Generated by Django 5.2.3 on 2025-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=500)),
                ('weight', models.FloatField()),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
    ]
