# Generated by Django 5.2.3 on 2025-09-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('quantity', models.IntegerField(default=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.item')),
            ],
        ),
    ]
